apiVersion: v2
kind: ConfigMap
metadata:
  name: app-cm
  namespace: django-app
data:
  DB_HOST: "192.168.0.238"
  DB_USERNAME: "autosdb"
  DB_PASSWORD: "~N1ghtT3mpo@"
  DB_NAME: "autosdb"
  DB_PORT: "5432"
  STATIC_ROOT: "/data/static"