apiVersion: batch/v1
kind: Job
metadata:
  name: django-db-migrations
  namespace: django-app
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 60

  template:
    spec:
      containers:
        - name: migration-container
          image: 192.168.0.161:32000/auto-django
          command: ['python', 'manage.py', 'migrate']
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8000
      restartPolicy: OnFailure
  backoffLimit: 3