apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: django-app
data:
  default.conf: |
    server {
      listen 80;
      server_name 172.16.50.200 localhost;

      location = /favicon.ico {access_log off; log_not_found off;}
      location /static/ {
        root /autosstatic;
      }

      location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
      }
    }