apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx-cm
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
        - name: empty
          emptyDir:
            sizeLimit: 0
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: empty
              readOnly: true
            - mountPath: /etc/nginx/proxy_params
              subPath: proxy_params
              name: nginx
              readOnly: true
            - mountPath: /etc/nginx/sites-available/autos
              subPath: autos
              name: nginx
              readOnly: true
            - mountPath: /etc/nginx/sites-available/default
              subPath: default
              name: nginx
              readOnly: true
            - mountPath: "/data/static"
              name: staticfiles
